Welcome to the WebAppDIRAC wiki!

 - How to setup your eclipse `<https://github.com/DIRACGrid/WebAppDIRAC/wiki/How-to-setup-Eclipse-for-developing-ExtJs>`_
 - `User Documentation <https://github.com/DIRACGrid/WebAppDIRAC/wiki/DIRAC-WebApp>`_

 - `How to create new applications <https://github.com/DIRACGrid/WebAppDIRAC/wiki/How-to-create-new-web-application-within-the-DIRAC-web-framework>`_

 - `Asynchronous handling mechanisms of clients' requests <https://github.com/DIRACGrid/WebAppDIRAC/wiki/Asynchronous-handling-mechanisms-of-clients%27-requests>`_

 - `Roadmap <https://github.com/DIRACGrid/WebAppDIRAC/wiki/Apps-to-do>`_

RFC:
----
   `Requests For Comments <https://github.com/DIRACGrid/WebAppDIRAC/wiki/DIRAC-Requests-For-Comments-%28RFC%29>`_